import { Category, MetroLine } from "@/types";
import {
  Clock,
  MessageSquare,
  Shield,
  Sparkles,
  Train,
  Users,
  Wrench,
} from "lucide-react";

export const CATEGORIES: Category[] = [
  {
    id: "seguridad",
    name: "Seguridad",
    icon: Shield,
    weight: 0.3,
    color: "#ef4444",
  },
  {
    id: "puntualidad",
    name: "Puntualidad",
    icon: Clock,
    weight: 0.25,
    color: "#f59e0b",
  },
  {
    id: "limpieza",
    name: "Limpieza",
    icon: Sparkles,
    weight: 0.15,
    color: "#10b981",
  },
  {
    id: "comodidad",
    name: "Comodidad",
    icon: Users,
    weight: 0.1,
    color: "#6366f1",
  },
  {
    id: "comunicacion",
    name: "Comunicación",
    icon: MessageSquare,
    weight: 0.1,
    color: "#8b5cf6",
  },
  {
    id: "fallas",
    name: "Fallas Técnicas",
    icon: Wrench,
    weight: 0.05,
    color: "#06b6d4",
  },
  {
    id: "saturacion",
    name: "Saturación",
    icon: Train,
    weight: 0.05,
    color: "#ec4899",
  },
];

export const METRO_LINES: MetroLine[] = [
  {
    id: "L1",
    name: "Línea 1",
    color: "#e91e8b",
    stations: [
      { id: "obs", name: "Observatorio", x: 50, y: 280 },
      { id: "tac", name: "Tacubaya", x: 110, y: 280 },
      { id: "jua", name: "Juanacatlán", x: 150, y: 280 },
      { id: "cha", name: "Chapultepec", x: 190, y: 280 },
      { id: "sev", name: "Sevilla", x: 230, y: 280 },
      { id: "ins", name: "Insurgentes", x: 280, y: 280 },
      { id: "cua", name: "Cuauhtémoc", x: 330, y: 280 },
      { id: "bal", name: "Balderas", x: 380, y: 280 },
      { id: "sal", name: "Salto del Agua", x: 420, y: 280 },
      { id: "isa", name: "Isabel la Católica", x: 460, y: 280 },
      { id: "pid", name: "Pino Suárez", x: 500, y: 280 },
      { id: "mer", name: "Merced", x: 540, y: 280 },
      { id: "can", name: "Candelaria", x: 580, y: 280 },
      { id: "sla", name: "San Lázaro", x: 630, y: 280 },
      { id: "moc", name: "Moctezuma", x: 680, y: 280 },
      { id: "zar", name: "Zaragoza", x: 730, y: 280 },
      { id: "pan", name: "Pantitlán", x: 790, y: 280 },
    ],
  },
  {
    id: "L2",
    name: "Línea 2",
    color: "#0054a6",
    stations: [
      { id: "cua2", name: "Cuatro Caminos", x: 180, y: 80 },
      { id: "pan2", name: "Panteones", x: 180, y: 120 },
      { id: "tac2", name: "Tacuba", x: 180, y: 160 },
      { id: "col", name: "Colegio Militar", x: 180, y: 200 },
      { id: "nor", name: "Normal", x: 180, y: 240 },
    ],
  },
  {
    id: "L3",
    name: "Línea 3",
    color: "#b59b28",
    stations: [
      { id: "ind", name: "Indios Verdes", x: 420, y: 50 },
      { id: "dep", name: "Deportivo 18 de Marzo", x: 420, y: 90 },
      { id: "pot", name: "Potrero", x: 420, y: 130 },
    ],
  },
];

export const PALABRAS_CLAVE: Record<string, string[]> = {
  seguridad: [
    "ROBOS",
    "ASALTOS",
    "ACOSO",
    "INSEGURO",
    "MIEDO",
    "PELEAS",
    "DROGAS",
    "VENDEDORES",
    "MANOSEO",
    "CARTERISTAS",
  ],
  puntualidad: [
    "RETRASOS",
    "TARDANZA",
    "LENTO",
    "ESPERA",
    "DEMORA",
    "TIEMPO",
    "HORARIO",
    "IMPUNTUAL",
    "FALTA",
    "TREN",
  ],
  limpieza: [
    "SUCIO",
    "BASURA",
    "OLOR",
    "ASQUEROSO",
    "COCHINO",
    "INMUNDO",
    "MUGRE",
    "DESASTRE",
    "PESTILENTE",
    "HIGIÉNICO",
  ],
  comodidad: [
    "LLENO",
    "CALOR",
    "ASIENTOS",
    "APRETADO",
    "SOFOCANTE",
    "INCÓMODO",
    "ASFIXIA",
    "EMPUJONES",
    "ESTRECHO",
    "HACINAMIENTO",
  ],
  comunicacion: [
    "CONFUSO",
    "AVISOS",
    "SEÑALES",
    "INFORMACIÓN",
    "ANUNCIOS",
    "MAPAS",
    "INDICACIONES",
    "DESORIENTADO",
    "PERDIDO",
    "INSTRUCCIONES",
  ],
  fallas: [
    "ESCALERAS",
    "AIRE",
    "PUERTAS",
    "ELEVADOR",
    "TORNIQUETES",
    "DESCOMPUESTO",
    "ROTO",
    "AVERÍA",
    "MANTENIMIENTO",
    "FALLA",
  ],
  saturacion: [
    "SATURADO",
    "ABARROTADO",
    "CAOS",
    "MULTITUD",
    "COLAPSO",
    "SOBRECUPO",
    "ATASCADO",
    "REPLETO",
    "DESBORDADO",
    "APRETUJADO",
  ],
};

export const FRASES_EJEMPLO: Record<string, string[]> = {
  ROBOS: ["Me robaron el celular", "Cuidado con los rateros", "Robo constante"],
  ASALTOS: [
    "Me asaltaron a punta de cuchillo",
    "Zona peligrosa",
    "Asaltos frecuentes",
  ],
  ACOSO: [
    "Me acosaron en el vagón",
    "Mucho acoso sexual",
    "Incomodidad constante",
  ],
  SUCIO: [
    "Está asqueroso el piso",
    "Huele muy mal",
    "Necesita limpieza urgente",
  ],
  BASURA: [
    "Mucha basura acumulada",
    "Tiran basura por todos lados",
    "Falta de botes",
  ],
  OLOR: [
    "Olor insoportable",
    "Apesta horrible",
    "Necesitan ventilación urgente",
  ],
  RETRASOS: [
    "Llevo 20 min esperando",
    "El tren no pasa",
    "Siempre con retrasos",
  ],
  TARDANZA: ["Muy tardado", "Demora excesiva", "Nunca es puntual"],
  LENTO: ["Servicio muy lento", "Va a vuelta de rueda", "Demasiado lento"],
  LLENO: ["Imposible subir", "Iba como sardina", "No cabe ni un alfiler"],
  CALOR: ["Calor insoportable", "Se siente como sauna", "Asfixiante el calor"],
  ASIENTOS: ["No hay asientos", "Todos los asientos rotos", "Faltan asientos"],
  ESCALERAS: [
    "Escaleras sin funcionar",
    "Otra vez descompuestas",
    "Siempre fuera de servicio",
  ],
  AIRE: ["No hay aire acondicionado", "Clima descompuesto", "Sin ventilación"],
  PUERTAS: ["Puertas trabadas", "No cierran bien", "Peligro con las puertas"],
  SATURADO: ["Demasiada gente", "Colapsó la estación", "Saturación extrema"],
  ABARROTADO: [
    "Está abarrotadísimo",
    "No se puede ni respirar",
    "Lleno a reventar",
  ],
  CAOS: ["Es un caos total", "Desorganización completa", "Mucho desorden"],
  CONFUSO: [
    "Muy confuso el mapa",
    "No entiendo las señales",
    "Desorientación total",
  ],
  AVISOS: [
    "No hay avisos claros",
    "Falta información",
    "Avisos incomprensibles",
  ],
  SEÑALES: ["Señalización deficiente", "Faltan señales", "Señales borrosas"],
};
