import { Category, MetroLine } from "@/types";
import {
  Clock,
  MessageSquare,
  Shield,
  Sparkles,
  Train,
  Users,
  Wrench,
} from "lucide-react";

export const CATEGORIES: Category[] = [
  {
    id: "seguridad",
    name: "Seguridad",
    icon: Shield,
    weight: 0.3,
    color: "#ef4444",
  },
  {
    id: "puntualidad",
    name: "Puntualidad",
    icon: Clock,
    weight: 0.25,
    color: "#f59e0b",
  },
  {
    id: "limpieza",
    name: "Limpieza",
    icon: Sparkles,
    weight: 0.15,
    color: "#10b981",
  },
  {
    id: "comodidad",
    name: "Comodidad",
    icon: Users,
    weight: 0.1,
    color: "#6366f1",
  },
  {
    id: "comunicacion",
    name: "Comunicación",
    icon: MessageSquare,
    weight: 0.1,
    color: "#8b5cf6",
  },
  {
    id: "fallas",
    name: "Fallas Técnicas",
    icon: Wrench,
    weight: 0.05,
    color: "#06b6d4",
  },
  {
    id: "saturacion",
    name: "Saturación",
    icon: Train,
    weight: 0.05,
    color: "#ec4899",
  },
];

export const METRO_LINES: MetroLine[] = [];

// Datos simulados de reportes y gravedad por estación
// severity: 0.0 = sin gravedad (sin rojo), 1.0 = gravedad máxima (rojo intenso)
export const STATION_REPORT_DATA: Record<
  string,
  { reportCount: number; severity: number; recentIssue: string }
> = {
  // Línea 2 - Azul (variación de 0.05 a 1.0 para ver toda la gama de colores)
  cua2: {
    reportCount: 25,
    severity: 0.08,
    recentIssue: "Falta de mapas impresos",
  },
  pan2: {
    reportCount: 65,
    severity: 0.78,
    recentIssue: "Acoso sexual constante",
  },
  tac2: { reportCount: 92, severity: 1.0, recentIssue: "Robos frecuentes" },
  col: {
    reportCount: 12,
    severity: 0.05,
    recentIssue: "Pequeñas mejoras pendientes",
  },
  nor: { reportCount: 82, severity: 0.88, recentIssue: "Retrasos y asaltos" },
  smc: { reportCount: 78, severity: 0.85, recentIssue: "Acoso en vagones" },
  rev: {
    reportCount: 30,
    severity: 0.15,
    recentIssue: "Baja conectividad WiFi",
  },
  hid: { reportCount: 88, severity: 0.95, recentIssue: "Asaltos reportados" },
  bea: {
    reportCount: 90,
    severity: 0.92,
    recentIssue: "Inseguridad y saturación",
  },
  all: { reportCount: 22, severity: 0.18, recentIssue: "Falta información" },
  zoc: { reportCount: 95, severity: 0.98, recentIssue: "Inseguridad grave" },
  pid2: { reportCount: 82, severity: 0.9, recentIssue: "Carteristas activos" },
  saa: { reportCount: 75, severity: 0.82, recentIssue: "Peleas frecuentes" },
  cha2: {
    reportCount: 70,
    severity: 0.75,
    recentIssue: "Vendedores ambulantes",
  },
  vip: { reportCount: 28, severity: 0.1, recentIssue: "Señalización antigua" },
  xol: {
    reportCount: 20,
    severity: 0.06,
    recentIssue: "Pocos asientos libres",
  },
  vil: { reportCount: 88, severity: 0.94, recentIssue: "Zona peligrosa" },
  ntz: {
    reportCount: 35,
    severity: 0.22,
    recentIssue: "Temperatura ambiente alta",
  },
  por: {
    reportCount: 95,
    severity: 0.96,
    recentIssue: "Asaltos violentos",
  },
  erm: { reportCount: 78, severity: 0.86, recentIssue: "Robos con violencia" },
  gen: { reportCount: 85, severity: 0.89, recentIssue: "Inseguridad crítica" },
  tas: { reportCount: 92, severity: 0.93, recentIssue: "Zona de alto riesgo" },

  // Línea 12 - Dorada (variación continua para transiciones suaves)
  mix: { reportCount: 87, severity: 0.91, recentIssue: "Robos constantes" },
  ins12: { reportCount: 85, severity: 0.88, recentIssue: "Robos de celular" },
  hos: {
    reportCount: 32,
    severity: 0.09,
    recentIssue: "Elevador lento",
  },
  zap: {
    reportCount: 90,
    severity: 0.92,
    recentIssue: "Peleas entre pasajeros",
  },
  par: { reportCount: 25, severity: 0.07, recentIssue: "Basura en andenes" },
  eje: {
    reportCount: 95,
    severity: 0.97,
    recentIssue: "Acoso y asaltos",
  },
  erm12: { reportCount: 80, severity: 0.84, recentIssue: "Inseguridad grave" },
  mex: {
    reportCount: 72,
    severity: 0.79,
    recentIssue: "Robos frecuentes",
  },
  atl: { reportCount: 98, severity: 0.99, recentIssue: "Zona peligrosa" },
  cul: { reportCount: 38, severity: 0.14, recentIssue: "Iluminación débil" },
  sji: {
    reportCount: 28,
    severity: 0.11,
    recentIssue: "Falta personal de ayuda",
  },
  lom: { reportCount: 92, severity: 0.95, recentIssue: "Robos y saturación" },
  cen: { reportCount: 42, severity: 0.16, recentIssue: "Clima templado" },
  per: {
    reportCount: 88,
    severity: 0.91,
    recentIssue: "Asaltos a mano armada",
  },
  teo: {
    reportCount: 85,
    severity: 0.87,
    recentIssue: "Inseguridad constante",
  },
  oli: { reportCount: 30, severity: 0.13, recentIssue: "Necesita más mapas" },
  noe: {
    reportCount: 35,
    severity: 0.2,
    recentIssue: "Sanitarios por mejorar",
  },
  zap12: {
    reportCount: 90,
    severity: 0.93,
    recentIssue: "Zona de alto peligro",
  },
  tla: { reportCount: 94, severity: 0.96, recentIssue: "Asaltos violentos" },
  tzi: { reportCount: 88, severity: 0.9, recentIssue: "Asaltos violentos" },
};

export const PALABRAS_CLAVE: Record<string, string[]> = {
  seguridad: [
    "ROBOS",
    "ASALTOS",
    "ACOSO",
    "INSEGURO",
    "MIEDO",
    "PELEAS",
    "DROGAS",
    "VENDEDORES",
    "MANOSEO",
    "CARTERISTAS",
  ],
  puntualidad: [
    "RETRASOS",
    "TARDANZA",
    "LENTO",
    "ESPERA",
    "DEMORA",
    "TIEMPO",
    "HORARIO",
    "IMPUNTUAL",
    "FALTA",
    "TREN",
  ],
  limpieza: [
    "SUCIO",
    "BASURA",
    "OLOR",
    "ASQUEROSO",
    "COCHINO",
    "INMUNDO",
    "MUGRE",
    "DESASTRE",
    "PESTILENTE",
    "HIGIÉNICO",
  ],
  comodidad: [
    "LLENO",
    "CALOR",
    "ASIENTOS",
    "APRETADO",
    "SOFOCANTE",
    "INCÓMODO",
    "ASFIXIA",
    "EMPUJONES",
    "ESTRECHO",
    "HACINAMIENTO",
  ],
  comunicacion: [
    "CONFUSO",
    "AVISOS",
    "SEÑALES",
    "INFORMACIÓN",
    "ANUNCIOS",
    "MAPAS",
    "INDICACIONES",
    "DESORIENTADO",
    "PERDIDO",
    "INSTRUCCIONES",
  ],
  fallas: [
    "ESCALERAS",
    "AIRE",
    "PUERTAS",
    "ELEVADOR",
    "TORNIQUETES",
    "DESCOMPUESTO",
    "ROTO",
    "AVERÍA",
    "MANTENIMIENTO",
    "FALLA",
  ],
  saturacion: [
    "SATURADO",
    "ABARROTADO",
    "CAOS",
    "MULTITUD",
    "COLAPSO",
    "SOBRECUPO",
    "ATASCADO",
    "REPLETO",
    "DESBORDADO",
    "APRETUJADO",
  ],
};

export const FRASES_EJEMPLO: Record<string, string[]> = {
  ROBOS: ["Me robaron el celular", "Cuidado con los rateros", "Robo constante"],
  ASALTOS: [
    "Me asaltaron a punta de cuchillo",
    "Zona peligrosa",
    "Asaltos frecuentes",
  ],
  ACOSO: [
    "Me acosaron en el vagón",
    "Mucho acoso sexual",
    "Incomodidad constante",
  ],
  SUCIO: [
    "Está asqueroso el piso",
    "Huele muy mal",
    "Necesita limpieza urgente",
  ],
  BASURA: [
    "Mucha basura acumulada",
    "Tiran basura por todos lados",
    "Falta de botes",
  ],
  OLOR: [
    "Olor insoportable",
    "Apesta horrible",
    "Necesitan ventilación urgente",
  ],
  RETRASOS: [
    "Llevo 20 min esperando",
    "El tren no pasa",
    "Siempre con retrasos",
  ],
  TARDANZA: ["Muy tardado", "Demora excesiva", "Nunca es puntual"],
  LENTO: ["Servicio muy lento", "Va a vuelta de rueda", "Demasiado lento"],
  LLENO: ["Imposible subir", "Iba como sardina", "No cabe ni un alfiler"],
  CALOR: ["Calor insoportable", "Se siente como sauna", "Asfixiante el calor"],
  ASIENTOS: ["No hay asientos", "Todos los asientos rotos", "Faltan asientos"],
  ESCALERAS: [
    "Escaleras sin funcionar",
    "Otra vez descompuestas",
    "Siempre fuera de servicio",
  ],
  AIRE: ["No hay aire acondicionado", "Clima descompuesto", "Sin ventilación"],
  PUERTAS: ["Puertas trabadas", "No cierran bien", "Peligro con las puertas"],
  SATURADO: ["Demasiada gente", "Colapsó la estación", "Saturación extrema"],
  ABARROTADO: [
    "Está abarrotadísimo",
    "No se puede ni respirar",
    "Lleno a reventar",
  ],
  CAOS: ["Es un caos total", "Desorganización completa", "Mucho desorden"],
  CONFUSO: [
    "Muy confuso el mapa",
    "No entiendo las señales",
    "Desorientación total",
  ],
  AVISOS: [
    "No hay avisos claros",
    "Falta información",
    "Avisos incomprensibles",
  ],
  SEÑALES: ["Señalización deficiente", "Faltan señales", "Señales borrosas"],
};
